//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyClass
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public bool stop { get; set; }
        public int Tag_id { get; set; }
        public string Title { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual MyTag MyTag { get; set; }
    }
}
